export const carData = [
  {
    id: 0,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/2015_Mazda_MX-5_ND_2.0_SKYACTIV-G_160_i-ELOOP_Rubinrot-Metallic_Vorderansicht.jpg/400px-2015_Mazda_MX-5_ND_2.0_SKYACTIV-G_160_i-ELOOP_Rubinrot-Metallic_Vorderansicht.jpg",
    title: "Mazda MX-5",
    start_production: 1989,
    car_type: "Sports car Roadster",
    price: "15.44 Lakh",
    Seating_Capacity: 2,
    Fuel: "Petrol",
    Mileage: "19.0 kmpl",
    Transmission: "Manual",
    color: "brown",
    company: "Mazda",
  },
  {
    id: 1,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/2014_Porsche_Cayenne_%2892A_MY14%29_GTS_wagon_%282015-08-07%29_01.jpg/400px-2014_Porsche_Cayenne_%2892A_MY14%29_GTS_wagon_%282015-08-07%29_01.jpg",
    title: "Porsche Cayenne",
    start_production: 2002,
    car_type: "Mid-size luxury crossover SUV",
    price: "1.26 Crore",
    Seating_Capacity: 5,
    Fuel: "Petrol & Hybrid",
    Mileage: "19.0 kmpl",
    Transmission: "Manual",
    color: "white",
    company: "Porsche",
  },
  {
    id: 2,
    image:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Vintage_car_at_the_Wirral_Bus_%26_Tram_Show_-_DSC03336.JPG/400px-Vintage_car_at_the_Wirral_Bus_%26_Tram_Show_-_DSC03336.JPG",
    title: "Vauxhall Chevette",
    start_production: 1975,
    car_type: "Supermini",
    price: "1.6 Lakc",
    Seating_Capacity: 2,
    Fuel: "Petrol ",
    Mileage: "10.0 kmpl",
    Transmission: "Manual",
    color: "red",
    company: "Porsche",
  },
  {
    id: 4,
    image:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Jaguar_X-Type_Estate_front_20080731.jpg/400px-Jaguar_X-Type_Estate_front_20080731.jpg",
    title: "Jaguar X-Type",
    start_production: 2001,
    car_type: "Compact executive car",
    price: "14 Lakc",
    Seating_Capacity: 4,
    Fuel: "Petrol ",
    Mileage: "10.0 kmpl",
    Transmission: "Manual",
    color: "black",
    company: "Jaguar",
  },
  {
    id: 5,
    image:
    "https://ic1.maxabout.us/autos/cars_india/jaguar-43-x-type-196-x-type25-v6.jpg",
    title: "Jaguar X-Type",
    start_production: 2001,
    car_type: "Compact executive car",
    price: "14 Lakc",
    Seating_Capacity: 4,
    Fuel: "Petrol ",
    Mileage: "10.0 kmpl",
    Transmission: "Manual",
    color: "red",
    company: "Jaguar",
  },
  
];
